import { Geist, Geist_Mono } from "next/font/google";
import "../app/css/globals.css";
import "../app/css/color.css";
import Sidebar from "@/components/organisms/SideBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Sidebar/>
        {children}
      </body>
    </html>
  );
}
